### ISSUE TITLE
A good way to set bookmarks for Gmail maildir depending on context?

### ISSUE THREAD

**Issue by anaxonda** [danielfleischer/mu4easy#1]
Hello,

Much thanks for sharing your configuration here, its really helped me set up mu4e.

I am using your context generating macro, which for most cases works fine, except for Gmail 'Archive' directories, which are stored in 'gmail/All Mail' maildir.

Thus, in a gmail account context, when pressing 'ja' maildir bookmark opens to non-existent 'gmail/Archive'.

I have tried something like this:
```
(defvar my/mu4e-context (mu4e-context-current))

(cl-defmacro.....
(if (string-match-p "1gmail\\|2gmail\\|3gmail" my/mu4e-context)
(let
      ((inbox      (concat "/" maildir "/Inbox"))
       (sent       (concat "/" maildir "/Sent"))
       (trash      (concat "/" maildir "/Trash"))
       (refile     (concat "/" maildir "/All Mail"))
       (draft      (concat "/" maildir "/Drafts"))))
 (let
      ((inbox      (concat "/" maildir "/Inbox"))
       (sent       (concat "/" maildir "/Sent"))
       (trash      (concat "/" maildir "/Trash"))
       (refile     (concat "/" maildir "/Archive"))
       (draft      (concat "/" maildir "/Drafts")))))

...rest of macro
)
```
However my programming skills are very poor and I am unable to get it to work.
Is there an way to go about this that you recommend?

**Comment by danielfleischer** [comment]
Thank you for your kind words!

I've solved this issue by using the mbsync configuration file to "normalize" all the accounts folders' to be consistent. Have a look at the mbsync config in the readme file, especially these lines:

```
Channel Gmail-all
Far :Gmail-remote:"[Gmail]/All Mail"
Near :Gmail-local:"Archive"
CopyArrivalDate yes
Create Both
Expunge Both
SyncState *
```

They mean that the "All Mail" remote folder will be mapped to an "Archive" folder locally. If you're using something else other than mbsync, I don't know, but it should have similar options. Let me know if it solves your issue!

**Comment by anaxonda** [comment]
> I've solved this issue by using the mbsync configuration file to "normalize" all the accounts folders' to be consistent. Have a look at the mbsync config in the readme file, especially these lines:
>
> ```
> Channel Gmail-all
> Far :Gmail-remote:"[Gmail]/All Mail"
> Near :Gmail-local:"Archive"
> CopyArrivalDate yes
> Create Both
> Expunge Both
> SyncState *
> ```
>
> They mean that the "All Mail" remote folder will be mapped to an "Archive" folder locally. If you're using something else other than mbsync, I don't know, but it should have similar options. Let me know if it solves your issue!

That did the trick nicely! I was sure there was an easier way to go
about it.
Cheers
