### ISSUE TITLE
Attempting to send an email fails with `554 5.0.0 Error: no such user`

### ISSUE THREAD

**Issue by shackra** [danielfleischer/mu4easy#11]
Hi!

Thank you for this package! I'm able to read my email on mu4e again. However, I noticed that sending email is impossible for some reason (it doesn't matter what provider is it; Proton or Gmail or Yahoo, it doesn't send my message).

I'm using:
- mu4e 1.12.6
- mu 1.12.6

Given this configuration:

```elisp
(use-package mu4easy
  :ensure t
  :bind ("C-c u" . mu4e)
  :hook (after-init . mu4easy-mode)
  :custom
  (mu4easy-signature "\nJorge Araya\n\nContacto:\n Telegram: t.me/shackra · Signal:sdfasdfasdf Shackra.28")
  (mu4e-update-interval nil)
  (mu4e-alert-email-notification-types '(count))
  (mu4easy-contexts `(
		      ,(mu4easy-context
			:c-name "personal"
			:maildir "principal"
			:mail "jorge@esavara.cr"
			:smtp "127.0.0.1"
			:smtp-port 1025)
		      ,(mu4easy-context
			:c-name  "gmail"
			:maildir "gmail"
			:mail    "shackrasislock0@gmail.com"
			:smtp "smtp.gmail.com"
			:sent-action delete)
		      ,(mu4easy-context
			:c-name "yahoo"
			:maildir "yahoo"
			:smtp "smtp.mail.yahoo.com"
			:mail "jorgejavieran@yahoo.com.mx")
		      ,(mu4easy-context
			:c-name "work"
			:maildir "work"
			:mail "jorge.araya@conductorone.com"
			:smtp "smtp.gmail.com"
			:sig "Jorge Araya\nGolang Software Developer"
			:sent-action delete)))
  :config
  (setq sendmail-program (executable-find "msmtp")
	message-sendmail-f-is-evil t
	message-sendmail-extra-arguments '("--read-envelope-from")))
```

And this email:

```
From: Jorge Javier Araya Navarro <jorge@esavara.cr>
To: jorgejavieran@yahoo.com.mx
Subject: prueba
Fcc: /home/jorge/Maildir/principal/Sent/cur/1728401105.8a6cf36d603958f6.woody:2,S
Date: Tue, 08 Oct 2024 09:25:20 -0600
Message-ID: <87zfne62hr.fsf@esavara.cr>
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \n:t tex:imagemagick d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: nil
:attachment: nil
:alternatives: (text html)
:END:
Hi,


-- 

Jorge Araya

Contacto:
 Telegram: t.me/shackra · Signal:sdfasdfasdf Shackra.28

Jorge Araya

Contacto:
 Telegram: t.me/shackra · Signal:sdfasdfasdf Shackra.28
```

(**yes, the signature is repeated for some reason**)

I get the following:

```
220 127.0.0.1 ESMTP Service Ready
250-Hello woody
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-STARTTLS
250-AUTH PLAIN LOGIN
250 SIZE
220 2.0.0 Ready to start TLS
250-Hello woody
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH PLAIN LOGIN
250 SIZE
MAIL FROM:<jorge@esavara.cr> SIZE=734
250 2.0.0 Roger, accepting mail from <jorge@esavara.cr>
RCPT TO:<jorgejavieran@yahoo.com.mx>
250 2.0.0 I'll make sure <jorgejavieran@yahoo.com.mx> gets this
DATA
354 2.0.0 Go ahead. End your data with <CR><LF>.<CR><LF>
From: Jorge Javier Araya Navarro <jorge@esavara.cr>
To: jorgejavieran@yahoo.com.mx
Subject: prueba
Date: Tue, 08 Oct 2024 09:25:20 -0600
Message-ID: <87zfne62hr.fsf@esavara.cr>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: quoted-printable

#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil=20
 email:nil \n:t tex:imagemagick d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: nil
:attachment: nil
:alternatives: (text html)
:END:
Hi,


--=20

Jorge Araya

Contacto:
 Telegram: t.me/shackra =C2=B7 Signal:sdfasdfasdf Shackra.28

Jorge Araya

Contacto:
 Telegram: t.me/shackra =C2=B7 Signal:sdfasdfasdf Shackra.28
.
554 5.0.0 Error: no such user
QUIT
221 2.0.0 Bye

Process smtpmail connection broken by remote peer
```

**Comment by shackra** [comment]
With

```elisp
	message-send-mail-function #'message-send-mail-with-sendmail
	send-mail-function #'message-send-mail-with-sendmail
	message-sendmail-extra-arguments '("--read-envelope-from")
```

email is sent successfully

however, org-mode related things are still in the body:

![image](https://github.com/user-attachments/assets/477636e7-0d4f-4bfb-8f58-1c0ed6228d9e)

**Comment by danielfleischer** [comment]
Hi! here are some comments from the top of my head:

- Seeing the raw org text in your gmail means org-msg didn't create an HTML. What version are you running? install the latest which includes an update for mu 1.12.
- Secondly, I didn't test 1.12.6. Try to install 1.12.5 and see if you still see an issue.
- Question: why are you using the `msmtp` library for sending email and not the built-in SMTP library in Emacs. As you have troubles sending email, I would try to see if that's at fault. In fact, that's the first thing I would try: a different SMTP engine.

**Comment by shackra** [comment]
> Seeing the raw org text in your gmail means org-msg didn't create an HTML. What version are you running? install the latest which includes an update for mu 1.12.

it turns out that org-msg-edit-mode wasn't called, calling it and sending the email works as expected.

> Question: why are you using the `msmtp` library for sending email and not the built-in SMTP library in Emacs. As you have troubles sending email, I would try to see if that's at fault. In fact, that's the first thing I would try: a different SMTP engine.

that's because [I use home-manager](https://gitlab.com/shackra/puntoarchivos/-/blob/master/homes/woody/home.nix?ref_type=heads#L165), and it generates my email configuration not only for `mbsync`, but also for other goodies as `goimapnotify` (I'm the author, btw) and `msmtp`

**Comment by shackra** [comment]
what if `mu4easy-customize-org-msg` is what's inserting my signature twice?

**Comment by danielfleischer** [comment]
I think you need to set `message-signature` (or obsolete `mu4e-compose-signature`) to nil in order to prevent a duplicate signature.

**Comment by shackra** [comment]
Empty Message

**Comment by shackra** [comment]
sorry, the previous message was supposed to be an email I have written from mu4e lol...

Currently this is my configuration:

```
(defun shackra/change-message-send-mail-function ()
  "Cambia con qué se envia un email en mu4e"
  (setq message-send-mail-function #'message-send-mail-with-sendmail))

(use-package mu4easy
  :ensure t
  :bind ("C-c u" . mu4e)
  :hook ((after-init . mu4easy-mode)
	 (mu4easy-mode . shackra/change-message-send-mail-function)
	 (mu4e-compose-mode . org-msg-edit-mode))
  :custom
  (mu4easy-signature "Jorge Araya\n\nContacto:\n Telegram: t.me/shackra · Signal: Shackra.28")
  (mu4easy-download-dir "~/Descargas")
  (mu4easy-accounts '("principal" "gmail" "yahoo" "work"))
  (mu4easy-greeting nil)
  (org-msg-greeting-fmt nil)
  (mu4e-update-interval nil)
  (mu4e-alert-email-notification-types '(count))
  (sendmail-program (executable-find "msmtp"))
  (message-sendmail-f-is-evil t)
  (send-mail-function #'message-send-mail-with-sendmail)
  (message-sendmail-extra-arguments '("--read-envelope-from"))
  (mu4easy-contexts `(,(mu4easy-context
			:c-name "personal"
			:maildir "principal"
			:mail "jorge@esavara.cr")
		      ,(mu4easy-context
			:c-name  "gmail"
			:maildir "gmail"
			:mail    "shackrasislock0@gmail.com"
			:sent-action delete)
		      ,(mu4easy-context
			:c-name "yahoo"
			:maildir "yahoo"
			:mail "jorgejavieran@yahoo.com.mx")
		      ,(mu4easy-context
			:c-name "work"
			:maildir "work"
			:mail "jorge.araya@conductorone.com"
			:sig "Jorge Araya\nGolang Software Developer"
			:sent-action delete))))

```

and as you can see, it sends empty emails :)

**Comment by danielfleischer** [comment]
I don't know where you're going with the previous message but if you start from the start and set `message-signature` to nil, can you sent emails with a single signature? let me know so I can close the issue with this fix.

**Comment by shackra** [comment]
I just ditched mu4easy towards going small and step by step. I did, however, borrow your macro.

El martes 08 de octubre del 2024, Daniel Fleischer escribió:

> I don't know where you're going with the previous message but if you start from the start and set
> message-signature to nil, can you sent emails with a single signature? let me know so I can close the issue with
> this fix.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
Jorge Araya

Contacto:
 Telegram: t.me/shackra · Signal: Shackra.28
