### ISSUE TITLE
PassCmd doesn't work in gmail config

### ISSUE THREAD

**Issue by Bio-finder** [danielfleischer/mu4easy#12]
Hello,
I have been trying to use your settings to make mbsync work but I can't figure out how to set up the PassCmd as the one you provide doensn't work for me.
`"gpg -q --for-your-eyes-only --no-tty -d ~/.authinfo.gpg | awk '/machine imap.gmail.com login a@gmail.com/ {print $NF}'"`
doesn't produce any output so there is not way to print my password. Do you have a newer setting that could fix this issue?
Best regards,
Benoît

**Comment by danielfleischer** [comment]
Hi,
- Did you fill `.authinfo.gpg` with your credentials in the appropriate [format](https://www.gnu.org/software/emacs/manual/html_mono/auth.html)?
- Did you use a dedicated app password, not the Google account password?
- Do you have gpg installed?
- Did you encrypted the file correctly?
- What does the command return?

**Comment by Bio-finder** [comment]
Hi,
When I use the following command: `gpg -q --for-your-eyes-only --no-tty -d ~/.authinfo.gpg ` it prints my password but  when I use the full command I don't get anything printed  which is my issue.

**Comment by danielfleischer** [comment]
No worries, app passwords are newish.

BTW, `PassCmd` is not a command but a parameter (like `Host`) in the configuration file; mbsync will run the string to generate the password, like you manually did.
