### ISSUE TITLE
 Can't send any mails

### ISSUE THREAD

**Issue by Bio-finder** [danielfleischer/mu4easy#13]
Hello,
I am trying to set mu4e and mu4easy to send email but at the moment I just managed to get emails.

Here is my .emacs config:

`(add-to-list 'load-path (expand-file-name "/usr/local/share/emacs/site-lisp/mu4e//"))
(require 'mu4e)

(setq mu4e-maildir "/home/name/Mail/Gmail")
(setq message-send-mail-function 'smtpmail-send-it)

(setf (alist-get 'refile mu4e-marks)
      '(:char ("r" . "▶")
              :prompt "refile"
              :dyn-target (lambda (target msg) (mu4e-get-refile-folder msg))
              ;; Notice the special treatment for Gmail.
              :action (lambda (docid msg target)
                        (let ((maildir (mu4e-message-field msg :maildir)))
                          (if (string-match-p "Gmail\\|Google" maildir)
                              (mu4e--server-remove docid)
                            (mu4e--server-move docid (mu4e--mark-check-target target) "+S-u-N"))))))

(cl-defmacro mu4easy-context (&key c-name  maildir mail smtp
                                   (smtp-mail mail)
                                   (smtp-port 587)
                                   (smtp-type 'starttls)
                                   (sent-action 'sent)
                                   (name "name")
                                   (sig "name"))
  (let
      ((inbox      (concat "/" maildir "/Inbox"))
       (sent       (concat "/" maildir "/Sent"))
       (trash      (concat "/" maildir "/Trash"))
       (refile     (concat "/" maildir "/Archive"))
       (draft      (concat "/" maildir "/Drafts")))

    `(make-mu4e-context
      :name ,c-name
      :match-func (lambda (msg)
                    (when msg
                      (string-match-p (concat "^/" ,maildir "/")
                                      (mu4e-message-field msg :maildir))))
      :vars '((user-mail-address . ,mail)
              (user-full-name . ,name)
              (mu4e-sent-folder . ,sent)
              (mu4e-drafts-folder . ,draft)
              (mu4e-trash-folder . ,trash)
              (mu4e-refile-folder . ,refile)
              (mu4e-sent-messages-behavior . ,sent-action)
              (smtpmail-stream-type . ,smtp-type)
              (smtpmail-smtp-service . ,smtp-port)
              (smtpmail-smtp-user . ,smtp-mail)
              (smtpmail-smtp-server . ,smtp)
              (smtpmail-debug-info . t)
              (smtpmail-debug-verbose . t)
              (org-msg-signature . ,sig)
              (mu4e-maildir-shortcuts .
                                      ((,inbox   . ?i)
                                       (,sent    . ?s)
                                       (,trash   . ?t)
                                       (,refile  . ?a)
                                       (,draft   . ?d)))))))
(setq mu4easy-contexts

      '((mu4easy-context
         :c-name  "Google"
         :maildir "Gmail"
         :mail    "name@gmail.com"
         :smtp    "smtp.gmail.com"
         :sent-action delete)))

(setq mu4e-get-mail-command "mbsync -a -V"
      mu4e-update-interval 120
      mu4e-headers-auto-update t)

(setq smtpmail-debug-info t)
(setq auth-source-debug t)
(setq smtpmail-smtp-server "smtp.gmail.com")
`

I send mails with the shortcut C-c C-c but all I get is saving a mail in drafts:
`Saving file /home/bbergkpinto/Mail/Gmail/Gmail/Drafts/cur/1729064095.8528e11f502bb28a.sbr3-l187:2,DS...
Wrote /home/bbergkpinto/Mail/Gmail/Gmail/Drafts/cur/1729064095.8528e11f502bb28a.sbr3-l187:2,DS`

Do you have an idea of what could be causing this behaviour? I think I forgot something in my config but I don't know what :(

**Comment by danielfleischer** [comment]
Do you have a `smtp.gmail.com` line in your authinfo file? it should look like the imap line but for sending emails.

**Comment by Bio-finder** [comment]
No, I have just my password in the file. How should I configure this file?

**Comment by danielfleischer** [comment]
Please read on how Emacs reads credentials in https://www.gnu.org/software/emacs/manual/html_mono/auth.html.

**Comment by Bio-finder** [comment]
Hello,
Sorry to continue to ask but I did this in my .authinfo file:

`machine imap.gmail.com login name@gmail.com port ssh password ******`

`machine smtp.gmail.com login name@gmail.com port ssh password ******`

but I've still the same issue...

**Comment by danielfleischer** [comment]
Try without the `port ssh` but it looks good.

**Comment by Bio-finder** [comment]
Hello,
Thanks for the support.  I tried to remove the things you said but nothing is going better. The same for removing the cached authinfo.

**Comment by Bio-finder** [comment]
Emacs : 29.4
mu4e: I can't manage to find the version but it's the github version that I built.

**Comment by Bio-finder** [comment]
my bad, I installed the last stable release and everything works!!
Thanks again for the assistance :)
