### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by linwaytin** [danielfleischer/mu4easy#3]
I still remember a few years ago I try to use `emacs` + `mbsync` to get emails from Google accounts. I took me a lot of time and it did not work well. Eventually I thought that dealing with emails in emacs is not a good idea, for this and other reasons. 

Anyway, I'm still glad to see that this package can make things easier! I would be happy if I had this tool at that time.

**Comment by danielfleischer** [comment]
Thank you! be the change, etc. A few years ago I decided I had to move all in to mu4e. I learned a lot and wanted to share it. At first it was a collection of code snippets and only recently I converted it into a package, my first. Anyways, hope it's useful for you and improve you work and life. Best!
