### ISSUE TITLE
how to use `mu4easy-org-msg-select-format`

### ISSUE THREAD

**Issue by shroomist** [danielfleischer/mu4easy#5]
I've seen hints that it should be possible to select format, eg plain text.
I'm sorry, I have little to no knowledge on `elisp`.

**Comment by danielfleischer** [comment]
You can customize the `org-msg-default-alternatives` variable and specify `text` for the different options.

**Comment by shroomist** [comment]
How would would I switch between plain and html when composing?

**Comment by danielfleischer** [comment]
Oops, you mean how to use my `mu4easy-org-msg-select-format` function? easy, just use the universal argument, i.e. `C-u` before composing new/reply/forward message. You should see what the format is, if you expand the properties drawer:
<img width="747" alt="Screen Shot 2023-09-02 at 10 24 35" src="https://github.com/danielfleischer/mu4easy/assets/22022514/c5c3ea18-91a4-4b14-97de-a0f8ac107774">

Of course, you can edit this also by hand.

**Comment by shroomist** [comment]
Exactly what I was looking for, thanks for clarifying!
