### ISSUE TITLE
mu4easy not being fully instantiated with 'use-package'

### ISSUE THREAD

**Issue by shroomist** [danielfleischer/mu4easy#6]
I've been using this package for a while, somehow I'm unable to setup this package so that it's run automatically when mu4e starts.

The behavior is such that the contexts seem to partially work (seems inconsistent, I couldn't pinpoint what's wrong with contexts),  when composing message it only launches the default compose, without the `org-msg` or other configurations that I have.

My workaround is to toggle `mu4easy-mode` manually after mu4e launched.

I'm on doomemacs distro, emacs 29.1.

**Comment by danielfleischer** [comment]
I'll try to investigate it. What's your config related to mu4easy?

**Comment by Moerliy** [comment]
I'm gonna charm in here too. I have the same issue.
mu4easy-mode does not want initiated. I even tried starting it with a init hook like after-init-hook (in my case with elpaca's init hook elpaca-after-init-hook). What does work tho is starting mu4easy-mode with mu4e-main-mode but that doesn't help with the mu4easy config for contexts.

My config related to mu:
```emacs-lisp
(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")
(require 'mu4e)
(setq user-mail-address "max@musterman.de")
(use-package mu4easy
  :bind ("C-c u" . mu4e)
  :config 
  (mu4easy-mode)
  :custom
  (setq mu4easy-contexts
	'((mu4easy-context
           :c-name  "Ionos"
           :maildir "Ionos"
           :mail    "max@musterman.de"
           :smtp    "smtp.ionos.de"))))

```

As a disclaimer I'm not thaaaaat good with plain emacs. Used doom before and started writing emacs from scratch now for a couple of weeks. If you need something and I know how to provide it I would gladly do that.

**Comment by danielfleischer** [comment]
@Moerliy thanks for chiming in; notice in your code, that's not the correct way of using the "custom" keyword. It has the following [form](https://github.com/jwiegley/use-package#customizing-variables):

```elisp
:custom 
(key1 value1 [doc1])
(key2 value2 [doc2])
...
```

**Comment by Moerliy** [comment]
@danielfleischer Thank you. That fixed the issue with the context not working for me. 
Although the mu4easy-mode still doesn't want to activate when starting emacs. I could use `:hook (mu4e-main-mode . mu4easy-mode)` but that comes with some other problem too.
