### ISSUE TITLE
how do you quickly jump to your gmail sent items?

### ISSUE THREAD

**Issue by japhir** [danielfleischer/mu4easy#7]
With this config where you don't sync the Sent folder for your gmail account (because it's already all available in the All Mail/Archive), how do you quickly jump to your sent emails for this account? Is there any way to set up the keyboard shortcut J-s to jump to the /Archive channel with a filter with something like from:<your email address>?

Cheers! I'm not using the package directly but have manually configured everything according to your setup! (I wanted to understand what was going on, so I didn't want to rely on macro's for now).

**Comment by danielfleischer** [comment]
I would say create a bookmark with the following query `from:daniel@gmail.com`; refine as needed. Let me know if that works. You can always modify mbsync to sync the sent email as last resort.

**Comment by japhir** [comment]
Hmm I didn't figure out how to create a context-specific bookmark only for that one gmail account. What I did instead was create a global bookmark for all sent mail from all my email addresses, rather than specific ones for each context.
